<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "cleantalk"
 *
 * Auto generated by Extension Builder 2015-05-30
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/
//print_r($GLOBALS['TYPO3_CONF_VARS']);
//print $GLOBALS['TYPO3_CONF_VARS']['EXT']['extConf']['cleantalk'];
//die();
$EM_CONF[$_EXTKEY] = array(
	'title' => 'CleanTalk antispam',
	'description' => 'Protect your site from spam',
	'category' => 'module',
	'author' => '',
	'author_email' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.2.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);